## BaseCart (object)
+ id:ByQpDBcM (required, string) - Unique Cart identifier.
+ expirationTime:2016-05-23T15:39:59.935Z (required, string) - The Cart expiration time.
+ items (required, array)

## Cart (BaseCart)
+ userId:uxxxxxxxxxx (required, string) - Unique User identifier.

## AnonymousCart (BaseCart)
+ userId:anonymous (required, string) - Allways 'anonymous' for an anonymmous Cart.

## CartEntryList (array)
+ (CartEntry)

## CartEntry
+ itemId: 1 (required, number) - Unique Entry identifier.

## Entry (object)
+  id:ByQpDBcM (required, string) - The Entry id.
+  productId:0001 (required, string) - The Entry Product id.
+  quantity:10 (required, number) - The Entry quantity.
+  reserves (optional, ReserveList) - The reserves list.

## ReserveList (array)
+ (CartReserve)

## CartReserve (object)
+ id:HJeJVjeX (required, string) - The Reserve id.
+ warehouseId:001 (required, string) - The reserve warehouse id.
+ quantity:10 (required, number) - The reserve quantity.
+ expirationTime:2016-05-23T15:39:59.935Z (required, string) - The reserve expiration time.

## NewCartRequest (object)
+ userId:uxxxxxxxxxx (optional, string) - The user id who will own the Cart.

## AddEntryRequest (object)
+  cartId:ByQpDBcM (required, string) - The Cart id to add an Entry. Only for RPC style. 
+  productId:0001 (required, string) - The product id to put in the Entry.
+  quantity:10 (required, number) - The quantity to put in the Entry.
+  warehouseId:001 (optional, string) - The warehouse id.

## RemoveEntryRequest (object)
+  cartId:ByQpDBcM (optional, string) - The Cart id to remove the Entry. Only for RPC style. 
+  entryId:ryLKuSJm (required, string) - The Entry id to remove. Only for RPC style. 
